### ISSUE TITLE
Failed to emerge net-print/cndrvcups-capt-2.71

### ISSUE THREAD

**Issue by pdraganov3** [homoludens/canoncapt-euilds#4]
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'cngplp/LICENSE*'
 * ERROR: net-print/cndrvcups-capt-2.71::CanonCAPT failed (install phase):
 *   dodoc failed

[build.log.GZ](https://github.com/homoludens/canoncapt-euilds/files/4008474/build.log.GZ)

**Comment by e-pirate** [comment]
Same for me.
